### PR TITLE
Add Base-16 colour selection exported from Base16-Builder

### PR DESCRIPTION
**Pull request by Luke-Nukem**

### CODE REVIEW

**Comment by actionless** [comment]
thanks a lot!

**Comment by actionless** [comment]
i just observed what some SEL_FG are too dark (ie not very contrast to SEL_BG) in about half of the themes, could you take a look on that?

**Comment by Luke-Nukem** [comment]
Sure, I'll start fixing up after exams. I was hoping to push them in so hopefully others could help with final tweaks. The thing about the base16-builder is that it's hard to make a "one size fits all" template, so it was better to get the initial pull in, then tweak individually, I know some of the colours are downright strange to see too.

**Comment by actionless** [comment]
@Luke-Nukem finally implemented it as a plugin:
https://github.com/actionless/oomox/commit/664d85d1e35a9299c3bf4223cf5e4c514b1dab9b

**Pull request merged**
