### PR TITLE
GUI: improve user experience with the dialogs

### PR DESCRIPTION
**Pull request by cwendling**

### CODE REVIEW

**Comment by actionless** [comment]
dialog response is `int` while `Gtk.ResponseType.<type>` is enum so comparing them with `is` will never return the expected result

**Comment by actionless** [comment]
that should help you:
```python
>>> Gtk.ResponseType.OK
<enum GTK_RESPONSE_OK of type Gtk.ResponseType>
>>> Gtk.ResponseType.OK.real
-5
```

**Comment by cwendling** [comment]
@actionless oops!  Indeed, you're right, of course.  I so carefully tried it for the cancellation cases I forgot to test the OK ones after changing that, sorry.  Fixed.

**Comment by actionless** [comment]
thanks, good job!

**Pull request merged**
