### PR TITLE
feat(gui: preview): add menus preview

### PR DESCRIPTION
**Pull request by cwendling**
Add menus to the preview.

### CODE REVIEW

**Comment by cwendling** [comment]
Wild hope: I'm not sure whether it'd be possible, but couldn't the preview use the real theme?  (maybe using [python-pyscss](https://pypi.python.org/pypi/pyScss/)?)  If possible, it would also fix menubar item borders and stuff like that.

**Comment by actionless** [comment]
`shade` in scss is all numix legacy, i am trying to replace them to `mix` everywhere (otherwise dark themes looking broken)

**Comment by actionless** [comment]
great job!
feel free to submit fixes for `shade` occurences in scss

**Comment by actionless** [comment]
regarding using scss for preview — my biggest concern is speed

**Comment by cwendling** [comment]
> feel free to submit fixes for `shade` occurences in scss

I finally (after reading GTK's code) found out what `shade()` actually does: multiply by `amount` the Lightness and Saturation components of the color.

So, about converting to `mix`, what would you see there?  In this case, the background mix makes it less contrasted: it adds 21% foreground to the background; so if we change the foreground to add some background to it, it'll lower the contrast even further.  Not sure it's a good idea.

Maybe mix some `white - bg` (so inverting the bg color) to it, so it brightens on a dark background and darkens on a light one?  Obviously that wouldn't be awesome with a plain gray background, but what can we do…

In the preview that could be:
```diff
diff --git a/gui/preview.py b/gui/preview.py
index 9acf276..03bcc74 100644
--- a/gui/preview.py
+++ b/gui/preview.py
@@ -24,6 +24,12 @@ class ThemePreview(Gtk.Grid):
                                                                colorscheme[a],
                                                                amount))
 
+        def mix_inverted(a, b, amount):
+            base = '%.6x' % (0xffffff - int(colorscheme[b], base=16))
+            return convert_theme_color_to_gdk(mix_theme_colors(base,
+                                                               colorscheme[a],
+                                                               amount))
+
         converted = {
             theme_value['key']: convert_theme_color_to_gdk(
                 colorscheme[theme_value['key']]
@@ -46,7 +52,9 @@ class ThemePreview(Gtk.Grid):
             self.override_color(item, self.FG, converted["MENU_FG"])
             self.override_color(item, self.BG, mix("MENU_BG", "MENU_FG", 0.21),
                                 state=Gtk.StateFlags.PRELIGHT)
-            # FIXME: :hover { color: shade("MENU_FG", 1.08); }
+            self.override_color(item, self.FG, mix_inverted("MENU_FG",
+                                                            "MENU_BG", 0.1),
+                                state=Gtk.StateFlags.PRELIGHT)
             for widget in self.get_menu_widgets(item.get_submenu()):
                 if isinstance(widget, Gtk.MenuShell):
                     self.override_color(widget, self.BG, converted["MENU_BG"])
```

> `shade` in scss is all numix legacy, i am trying to replace them to `mix` everywhere (otherwise dark themes looking broken)

Yeah when the amount is < 1 as it'll darken, but not when it is > 1 as it will lighten.  The current thing here for the menu is actually better on a dark background.

But I agree that having fixed lighten/darken is suboptimal, as indeed it doesn't respect whether the colors where dark or light in the first place.

**Comment by cwendling** [comment]
> regarding using scss for preview — my biggest concern is speed

Yeah that could be a problem indeed.  I might experiment a little if I get time and see if it could be reasonable.

**Comment by actionless** [comment]
i think mixing with inverted color could be a good way for some

i would like to add some screenshot-based tests to travis soon so it will be easier to control the theme changes with different colorschemes (ie to see the diff of screenshots of current and previous builds)

**Pull request merged**
