### PR TITLE
Fix menu toggle checks.

### PR DESCRIPTION
**Pull request by TiZ-EX1**
The fact that the last bug was in effect was hiding this one... insensitive checks were being shown on unchecked menuitems and vice versa!

I don't know why those other three commits are there.

### CODE REVIEW

**Comment by actionless** [comment]
i breaks unchecked checkboxes, see gtk3-widget-factory, top right hamburger button's menu

**Comment by actionless** [comment]
btw, what the issue it was intended to fix?

**Comment by TiZ-EX1** [comment]
I'm not seeing that issue on my side. There's no check when it's unchecked, then when I check it, the check appears. Maybe you're looking at 3.20's widget factory? It's broken there too now that I look at the source. Here, I'll fix it there too.

The issue this is intended to fix is where the insensitive checkbox displays on unchecked menu items, and where insensitive checked menu items show nothing.

**Comment by TiZ-EX1** [comment]
Actually now that I think about it, if the menuitem is insentive and unchecked, it shouldn't show anything at all.

**Comment by actionless** [comment]
no, i don't think so, how then to distinguish if it's a checkbox or action menu item?

the real problem here what there is no distinguish between inactive and unchecked menu asset,

so the solution will be to add the missing asset, will do that now

**Comment by TiZ-EX1** [comment]
That's a good point, but we can't distinguish between check menu items and action menu items as it is anyways; we have to distinguish from context.

**Comment by actionless** [comment]
try with 49c27cc6769a73ca4d53ca7a125ce43d1f7a3e2d now

**Comment by TiZ-EX1** [comment]
I like the idea, but it feels like with the opacity so high, the checked and unchecked states are so close together that they are nearly indistinguishable. I think what you meant to do is set the opacity to 0.1. That's just *barely* too dim; I'd recommend 0.15. I tried it out myself and it looks pretty good.

This will cause an inconsistency with GTK2... but it's not possible to get this effect in GTK2 at least with Murrine, so I think it's okay since an improved version of the toolkit should have improved usability.

**Comment by actionless** [comment]
which of them do you like to decrease, 0.5 to 0.15, right?

**Comment by TiZ-EX1** [comment]
No no, leave insensitive alone. It's perfect as is. Change the opacity in the unchecked ones from 0.9 to 0.15.

**Comment by TiZ-EX1** [comment]
I tried using Clearlooks to draw GtkCheckMenuItem on GTK2. It draws the entire checkbox... but then that affects the highlight too so that's no good. I think the low alpha checkbox is a good way to move forward, and GTK2 is just gonna have to deal with the potential ambiguity. Murrine themes have been doing that for years anyways and Cimi never fixed it, so people have been getting by and will continue to get by.

**Comment by actionless** [comment]
after some testing decided to make it a bit less transparent (0.20) since on some color combinations it became almost invisible:

c2e59538b7bbe9bb7b588cad9e42c4191b77e25e

**Comment by TiZ-EX1** [comment]
I think it still looks good that way, with opacity at 0.2.

I noticed we started using selected_bg_color for the checkboxes in menu items. That's consistent with other checkboxes, so I think that's a good idea. To make GTK2 match, add `text[NORMAL] = @selected_bg_color` to murrine-menu-item.

**Comment by actionless** [comment]
do you know any popular/small gtk2 apps where checkboxes are used in the menu?

in awf there are no any

**Comment by TiZ-EX1** [comment]
Geany uses menu checkboxes. It has preliminary gtk3 support, but I don't think any distro is building it with gtk3.

Also, I noticed that insensitive regular checkboxes look kind of weird because they use the fg color at full brightness. I hate to poke you further to do stuff, but could we also drop the opacity for the check on those to 0.5?

**Comment by actionless** [comment]
found already in pcmanfm-gtk2, fixed gtk2, thanks! :)

yup, i don't mind

**Comment by TiZ-EX1** [comment]
You're a cool dude to work with, thanks man. :+1:

**Comment by actionless** [comment]
done with insensitive: b198bd7dbae2531465c15ab0c3106be30314e7a6

thanks, looking better now

**Pull request closed without merging**
