### PR TITLE
GUI: Add internationalization support

### PR DESCRIPTION
**Pull request by cwendling**
Add i18n support (using gettext module) and an initial French translation.

`po.mk` might need to be enhanced, because although now it's nicely automatic, it might be annoying to update the `.po` automatically when the Python sources changes (well, when running `po.mk install`, which is the default), as the `.po` are checked in source yet partially generated and containing source references, and thus can lead to extra diff.  Not 100% sure what the best thing would be here… probably the same but not automatically rebuilding the `.po` when sources changes, but only with the `update-po` target.

Also, it could also be interesting to translate scripts at some point, which is totally doable using gettext, and should be straightforward to add to this infrastructure.

### CODE REVIEW

**Comment by actionless** [comment]
how can i test it?

seems i am doing smth wrong:

2017-03-01--1488391160_1717x738_scrot

**Comment by cwendling** [comment]
@actionless translations as used at runtime are generated, so you need to run `./po.mk` first.  After that, your command should work just fine (although I'd use `LANGUAGE=C ./gui.sh`, but both work)

**Comment by actionless** [comment]
looks good, don't you mind to also update `.gitignore` and `PKGBUILD`?

**Comment by cwendling** [comment]
@actionless Should be done, but I couldn't test the `PKGBUILD` yet, not having an Arch at hand.

**Comment by actionless** [comment]
sorry for asking you to mess with foreign-distro packaging but unless i've found some time to set up travis we need to have a reference setup scenario somewhere :)

**Comment by actionless** [comment]
thanks again!

**Comment by cwendling** [comment]
> sorry for asking you to mess with foreign-distro packaging but unless i've found some time to set up travis we need to have a reference setup scenario somewhere :)

No problem, if that work it was easy enough to find out and do that change.  And I agree that having a reference on how to set it up is important, I did read the PKGBUILD myself for reference.

**Pull request merged**
